# Generated by Django 2.1.4 on 2019-01-24 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='projects',
            new_name='Project',
        ),
    ]
